### ISSUE TITLE
Checking code with Gendarme

### ISSUE THREAD

**Issue by alvinseville7cf** [mono/mono#20954]
Hello! How to fix my ci.yml to check [MatrixUtils.cs](https://github.com/alvinseville7cf/TestCI/blob/main/MatrixUtils.cs) for bad code with [Gendarme](https://www.mono-project.com/docs/tools+libraries/tools/gendarme/)?
```yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Mono build
        run: |
          mcs -target:library -out:main.dll MatrixUtils.cs
    
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Gendarme check
        run: |
          sudo apt install gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt update

          sudo apt install mono-devel mono-complete

          gendarme MatrixUtils.cs
```
